{{- $components := omit .Values.components "flux" "helmRepositories" | values -}}

{{- range $components -}}
{{- if .enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ list . $ | include "skyfjell.common.format.component.namespace" }}
  labels:
    {{- include (printf "%s.labels" $.Chart.Name) $ | nindent 4 }}
    {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
