{{- $key := "tenant" -}}
{{- $parent := .Values.components.minio -}}
{{- $component := get $parent.components $key -}}
{{- $solution := .Values.solution -}}

{{- $repo := .Values.components.helmRepositories.components.minio -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}

{{- if and $parent.enabled $component.enabled (eq $solution.name "flux") -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list "minio" $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
    {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ list "minio" $component.name $ | include "platform-system.format.name" }}
  targetNamespace: {{ list $component . | include "skyfjell.common.format.component.namespace" }}
  dependsOn:
    {{- include "platform-system.require.dependencies" $ | nindent 4 }}
    - name: {{ list $parent.name $ | include "platform-system.format.name" }}
  chart:
    spec:
      chart: tenant
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ $solution.namespace | quote }}
  interval: {{ $solution.interval }}
  values:
{{- $defaultValues := ( include "platform-system.components.minio-tenant.defaultValues" $ | fromYaml ) }}
{{- mergeOverwrite $defaultValues $component.values | toYaml | nindent 4 }}
{{- end }}
