{{- $flux := .Values.components.flux -}}
{{- $kustomization := $flux.components.kustomization -}}
{{- if and $flux.enabled $kustomization.enabled -}}
{{- include "skyfjell.common.require.api.flux.kustomize" . -}}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{ list $kustomization.name . | include "platform-tenant.format.name.shared" }}
  namespace: {{ $flux.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
spec:
  sourceRef:
    kind: GitRepository
    name: {{ list . | include "platform-tenant.format.name.shared" }}
  serviceAccountName: {{ default (list . | include "platform-tenant.format.name.shared") .Values.components.serviceAccount.name }}
  {{- $customSpec := omit $kustomization.spec "serviceAccountName" "sourceRef" }}
  {{- $defaultSpec := (include "platform-tenant.kustomization.spec" . | fromYaml) }}
  {{- toYaml (merge $customSpec $defaultSpec) | nindent 2 }}
{{- end -}}
